refactor(commitlint): use brew commitlint utility based on npm pacakge

diff --git a/dot_commitlint/hooks/private_executable_commit-msg b/dot_commitlint/hooks/private_executable_commit-msg
--- a/dot_commitlint/hooks/private_executable_commit-msg
+++ b/dot_commitlint/hooks/private_executable_commit-msg
@@ -1,12 +1,11 @@
 #!/bin/sh
 
 if ! type commitlint >/dev/null 2>/dev/null; then
-	echo ""
-    echo "commitlint could not be found"
-    echo "try again after installing commitlint or add commitlint to PATH"
-	echo ""
-    exit 1;
+  echo ""
+  echo "commitlint could not be found"
+  echo "try again after installing commitlint or add commitlint to PATH"
+  echo ""
+  exit 1
 fi
 
-commitlint lint --message $1
-
+commitlint -g $HOME/.commitlint/commitlint.config.cjs -e $1
